name:                blockchain
version:             0.1.0.0
github:              "radrow/blockchain"
license:             BSD3
author:              "Radosław Rowicki"
maintainer:          "radrowicki@gmail.com"
copyright:           "2019 Radosław Rowicki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/radrow/blockchain#readme>

default-extensions:
  - TemplateHaskell
  - LambdaCase

dependencies:
- base
- hactors
- RSA
- lens
- mtl
- transformers
- hactors
- stm
- hashable-generics == 1.1.3
- hashable
- crypto-api

library:
  source-dirs: src

executables:
  blockchain-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain

tests:
  blockchain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain
